apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  annotations:
    configmanagement.gke.io/cluster-selector: selector-role-dev
  labels:
   role: dev
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
